import Mathlib

/-!
# Causal inheritance through certified compression

This module extracts the neutral logical core of causal presence used by the
positional-carry application.

A pattern is not declared present in a later carrier merely because the two
names were connected in a graph.  The system must provide:

* a primitive witness that a source carrier instantiates the pattern;
* a concrete witness for every direct compression step;
* a nonconstant observable action of the target carrier.

The transitive closure below stores the existence of every compression
certificate.  Consequently, causal presence can be inherited through a tower
of representations even when the original pattern is no longer displayed
explicitly at the final layer.

This is a logical schema.  It does not assert that every mathematical object
is generated by one distinguished pattern.  Such a conclusion is available
only for a concrete system after all required witnesses have been built.
-/

namespace CPFormal.Logic

universe u

/--
A family of observable carriers connected by certified compressions.

`PrimitiveWitness carrier pattern` records direct instantiation of a pattern.
`CompressionWitness source target` contains the mathematical evidence that
the target is a compressed realization of the source.
-/
structure CausalCompressionSystem where
  Pattern : Type u
  Carrier : Type u
  Input : Type u
  Output : Type u
  eval : Carrier → Input → Output
  PrimitiveWitness : Carrier → Pattern → Type u
  CompressionWitness : Carrier → Carrier → Type u
  ExplicitlyDisplays : Carrier → Pattern → Prop

namespace CausalCompressionSystem

variable (G : CausalCompressionSystem)

/--
Certified compression ancestry.  Every non-reflexive edge carries a
nonempty compression witness from the concrete system.
-/
inductive CompressionPath : G.Carrier → G.Carrier → Prop
  | refl (carrier : G.Carrier) :
      CompressionPath carrier carrier
  | tail {source middle target : G.Carrier} :
      CompressionPath source middle →
      Nonempty (G.CompressionWitness middle target) →
      CompressionPath source target

namespace CompressionPath

variable {G}

/-- Certified compression paths compose without discarding any edge witness. -/
theorem trans
    {source middle target : G.Carrier}
    (hsource : G.CompressionPath source middle)
    (htarget : G.CompressionPath middle target) :
    G.CompressionPath source target := by
  induction htarget with
  | refl =>
      exact hsource
  | tail hpath hedge ih =>
      exact CompressionPath.tail ih hedge

end CompressionPath

/--
A pattern is inherited by a target when it is instantiated by some source
carrier and a certified compression path reaches the target.
-/
def Reinstantiates
    (pattern : G.Pattern) (target : G.Carrier) : Prop :=
  ∃ source,
    Nonempty (G.PrimitiveWitness source pattern) ∧
      G.CompressionPath source target

/-- A carrier is operationally nontrivial when its observable is nonconstant. -/
def OperationallyNontrivial (carrier : G.Carrier) : Prop :=
  ∃ first second : G.Input,
    G.eval carrier first ≠ G.eval carrier second

/--
Causal presence through a carrier combines certified inheritance of the
pattern with a nontrivial observable action of that carrier.
-/
def CausallyPresentIn
    (pattern : G.Pattern) (carrier : G.Carrier) : Prop :=
  G.Reinstantiates pattern carrier ∧
    G.OperationallyNontrivial carrier

/--
The pattern is causally present but absent from the carrier's explicit surface
description.
-/
def HiddenButCausallyPresentIn
    (pattern : G.Pattern) (carrier : G.Carrier) : Prop :=
  G.CausallyPresentIn pattern carrier ∧
    ¬G.ExplicitlyDisplays carrier pattern

/-- Every primitive witness gives reflexive inheritance at its own carrier. -/
theorem reinstantiates_of_primitive
    {pattern : G.Pattern} {carrier : G.Carrier}
    (hprimitive : Nonempty (G.PrimitiveWitness carrier pattern)) :
    G.Reinstantiates pattern carrier := by
  exact ⟨carrier, hprimitive, CompressionPath.refl carrier⟩

/-- One certified compression step transports inherited presence. -/
theorem reinstantiates_of_compression
    {pattern : G.Pattern} {source target : G.Carrier}
    (hsource : G.Reinstantiates pattern source)
    (hcompression : Nonempty (G.CompressionWitness source target)) :
    G.Reinstantiates pattern target := by
  obtain ⟨root, hprimitive, hpath⟩ := hsource
  exact
    ⟨root, hprimitive,
      CompressionPath.tail hpath hcompression⟩

/-- An arbitrary certified path transports inherited presence. -/
theorem reinstantiates_of_path
    {pattern : G.Pattern} {source target : G.Carrier}
    (hsource : G.Reinstantiates pattern source)
    (hpath : G.CompressionPath source target) :
    G.Reinstantiates pattern target := by
  obtain ⟨root, hprimitive, hroot⟩ := hsource
  exact
    ⟨root, hprimitive,
      CompressionPath.trans hroot hpath⟩

/--
Causal presence is inherited along a certified path whenever the target
carrier itself has a nontrivial observable action.
-/
theorem causallyPresentIn_of_path
    {pattern : G.Pattern} {source target : G.Carrier}
    (hsource : G.CausallyPresentIn pattern source)
    (hpath : G.CompressionPath source target)
    (htarget : G.OperationallyNontrivial target) :
    G.CausallyPresentIn pattern target := by
  exact
    ⟨G.reinstantiates_of_path hsource.1 hpath, htarget⟩

/--
A system is generated by a pattern when every carrier has certified ancestry
from a primitive instance of that pattern.
-/
def GeneratedBy (pattern : G.Pattern) : Prop :=
  ∀ carrier, G.Reinstantiates pattern carrier

/--
Generation plus nontriviality yields causal presence throughout the system.
-/
theorem causallyPresentIn_all_of_generatedBy
    {pattern : G.Pattern}
    (hgenerated : G.GeneratedBy pattern)
    (hnontrivial :
      ∀ carrier, G.OperationallyNontrivial carrier) :
    ∀ carrier, G.CausallyPresentIn pattern carrier := by
  intro carrier
  exact ⟨hgenerated carrier, hnontrivial carrier⟩

/--
Explicit absence and causal presence are compatible when the two predicates
are kept distinct.
-/
theorem hiddenButCausallyPresentIn_of_witness
    {pattern : G.Pattern} {carrier : G.Carrier}
    (hcausal : G.CausallyPresentIn pattern carrier)
    (hhidden : ¬G.ExplicitlyDisplays carrier pattern) :
    G.HiddenButCausallyPresentIn pattern carrier :=
  ⟨hcausal, hhidden⟩

end CausalCompressionSystem

end CPFormal.Logic
