import CPFormal.Analytic.CpNativeCarryRealSpectralBoundaryCarrier

/-!
# Pre-compression witness for the native real carry boundary

`NativeCarryRealPlaneBoundaryClosesAt sigma time` remembers only the limit of
the finite camera resultants.  It no longer remembers the vector field that
was fed into those cameras, so the quadratic carry mass cannot be recovered
from that `Tendsto` alone.

This module keeps the missing data explicitly.  A pre-compression witness
contains

* the complete real-plane state before camera synthesis;
* its identification with the native carry-normalized orbit;
* every finite vector resultant and its exact camera provenance;
* the closing limit of those resultants.

There is no free radial exponent in the witness.  Its state is constructed
from the inverse carry mass, so preservation of

`energy (state n) = n⁻¹`

is a theorem about the witness rather than one of its fields.

An arbitrary radial readout at `(sigma,time)` is physically lifted only when
its uncompressed state is literally the state retained by such a witness.
That state-level lift forces `sigma = 1/2` before scalar camera compression.
The retained nonzero seed then supplies a characteristic direction in the
fixed real time-multiplication pencil.

The final section records the remaining guardrail: asserting that every raw
camera limit has this pre-compression lift is still equivalent to the old raw
zero-rigidity statement.  The new witness closes the physical arrow without
pretending that a compressed limit reconstructs data it discarded.
-/

namespace CPFormal.Analytic.Cp

noncomputable section

/-! ## The state-level physical witness -/

/--
Native boundary datum before finite camera synthesis.

The state and every finite resultant are retained as data.  Their provenance
fields identify them with the carry-normalized real orbit and its additive
camera, while `closes` records the limiting boundary observation.
-/
structure NativeCarryRealPrecompressionBoundaryWitness (time : ℝ) where
  state : ℤ → NativeCarryRealPlane
  state_eq_native :
    state = nativeCarryRealPlaneSample time
  finiteResultant : ℕ → NativeCarryRealPlane
  finiteResultant_eq_camera :
    finiteResultant =
      fun M => nativeCarryFiniteSaturatedChart 3 M state
  closes :
    Filter.Tendsto finiteResultant Filter.atTop (nhds 0)

namespace NativeCarryRealPrecompressionBoundaryWitness

variable {time : ℝ}

/-- Every retained positive sample has exactly the inverse carry mass. -/
theorem state_energy_eq_inverse
    (W : NativeCarryRealPrecompressionBoundaryWitness time)
    {n : ℤ} (hn : 0 < n) :
    nativeCarryRealPlaneEnergy (W.state n) = ((n : ℝ))⁻¹ := by
  rw [congrFun W.state_eq_native n]
  exact nativeCarryRealPlaneEnergy_sample time hn

/--
Mass preservation is generated by the witness construction; it is not an
extra admissibility hypothesis.
-/
theorem state_preserves_carry_mass
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    ∀ n : ℤ, 1 < n →
      nativeCarryRealPlaneEnergy (W.state n) = ((n : ℝ))⁻¹ := by
  intro n hn
  exact W.state_energy_eq_inverse (lt_trans (by norm_num) hn)

/-- The retained seed is the nonzero unit direction. -/
@[simp] theorem state_one
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    W.state 1 = ((1 : ℝ), (0 : ℝ)) := by
  rw [congrFun W.state_eq_native 1]
  simp [nativeCarryRealPlaneSample, nativeCarryRealPlaneSampleAt]

/-- Each stored resultant is exactly the camera of the retained native state. -/
theorem finiteResultant_eq_native_chart
    (W : NativeCarryRealPrecompressionBoundaryWitness time)
    (M : ℕ) :
    W.finiteResultant M =
      nativeCarryRealPlaneFiniteChart 3 M time := by
  rw [congrFun W.finiteResultant_eq_camera M, W.state_eq_native]
  rfl

/-- Forgetting the state recovers the old boundary limit at the critical mass. -/
theorem to_critical_boundary_closure
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    NativeCarryRealPlaneBoundaryClosesAt ((1 : ℝ) / 2) time := by
  unfold NativeCarryRealPlaneBoundaryClosesAt
  have hresultant :
      W.finiteResultant =
        fun M => nativeCarryRealPlaneFiniteChart 3 M time := by
    funext M
    exact W.finiteResultant_eq_native_chart M
  simpa only [hresultant, nativeCarryRealPlaneFiniteChart] using W.closes

/--
A critical raw closure has a canonical pre-compression witness.  No mass
hypothesis is supplied: the constructor fixes the native state itself.
-/
def ofCriticalBoundaryClosure
    (hclose :
      NativeCarryRealPlaneBoundaryClosesAt ((1 : ℝ) / 2) time) :
    NativeCarryRealPrecompressionBoundaryWitness time where
  state := nativeCarryRealPlaneSample time
  state_eq_native := rfl
  finiteResultant :=
    fun M => nativeCarryRealPlaneFiniteChart 3 M time
  finiteResultant_eq_camera := rfl
  closes := by
    unfold NativeCarryRealPlaneBoundaryClosesAt at hclose
    simpa only [nativeCarryRealPlaneFiniteChart] using hclose

/-! ## The retained state inside the fixed real spectral carrier -/

/-- The witness seed placed in the spectral fiber selected by its real time. -/
def spectralDirection
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    NativeCarryRealPlaneFamily ℝ :=
  fun r => if r = time then W.state 1 else 0

/-- The retained spectral direction is nonzero because its native seed is. -/
theorem spectralDirection_ne_zero
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    W.spectralDirection ≠ 0 := by
  intro hzero
  have hatTime := congrFun hzero time
  simp [spectralDirection, W.state_one] at hatTime

/--
The fixed time-multiplication relation contains the direction built from the
actual retained seed, not from a separately postulated vector.
-/
theorem spectralDirection_mem_time_relation
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    (W.spectralDirection,
        nativeCarryRealPlaneFamilyConformalAction
          time 0 W.spectralDirection) ∈
      nativeCarryRealTimeMultiplicationBoundaryPencil.relation := by
  change
    (W.spectralDirection,
        nativeCarryRealPlaneFamilyConformalAction
          time 0 W.spectralDirection) ∈
      LinearMap.range
        (nativeCarryRealTimeMultiplicationBoundaryPencil.valueTrace.prod
          nativeCarryRealTimeMultiplicationBoundaryPencil.fluxTrace)
  refine ⟨W.spectralDirection, ?_⟩
  apply Prod.ext
  · rfl
  · funext r
    by_cases hr : r = time
    · subst r
      simp [nativeCarryRealPlaneFamilyConformalAction]
    · simp [nativeCarryRealPlaneFamilyConformalAction,
        spectralDirection, hr]

/-- A physical pre-compression closure activates the fixed real pencil. -/
theorem to_timeMultiplicationRelationHasConformalSlope
    (W : NativeCarryRealPrecompressionBoundaryWitness time) :
    nativeCarryRealTimeMultiplicationBoundaryPencil.RelationHasConformalSlope
      time 0 :=
  ⟨W.spectralDirection, W.spectralDirection_ne_zero,
    W.spectralDirection_mem_time_relation⟩

end NativeCarryRealPrecompressionBoundaryWitness

/-! ## Physical closure as existence of retained vector data -/

/-- A closing native boundary for which the pre-compression state still exists. -/
def NativeCarryRealPrecompressionBoundaryClosesAt (time : ℝ) : Prop :=
  Nonempty (NativeCarryRealPrecompressionBoundaryWitness time)

/--
The witness predicate is exactly the critical raw closure, but carries
strictly more usable data than the bare proposition.
-/
theorem nativeCarryRealPrecompressionBoundaryClosesAt_iff
    (time : ℝ) :
    NativeCarryRealPrecompressionBoundaryClosesAt time ↔
      NativeCarryRealPlaneBoundaryClosesAt ((1 : ℝ) / 2) time := by
  constructor
  · rintro ⟨W⟩
    exact W.to_critical_boundary_closure
  · intro hclose
    exact ⟨
      NativeCarryRealPrecompressionBoundaryWitness.ofCriticalBoundaryClosure
        hclose⟩

/-- The physical closure activates the fixed pencil without a mass premise. -/
theorem precompressionBoundaryClosure_to_timePencil
    {time : ℝ}
    (hclose : NativeCarryRealPrecompressionBoundaryClosesAt time) :
    nativeCarryRealTimeMultiplicationBoundaryPencil.RelationHasConformalSlope
      time 0 := by
  rcases hclose with ⟨W⟩
  exact W.to_timeMultiplicationRelationHasConformalSlope

/-! ## Lifting an arbitrary radial readout before compression -/

/--
An arbitrary radial readout has a physical pre-compression lift when the
uncompressed sample field, not merely its camera limit, is the retained native
carry state.
-/
def NativeCarryRealPlaneBoundaryClosureHasPrecompressionLift
    (sigma time : ℝ) : Prop :=
  ∃ W : NativeCarryRealPrecompressionBoundaryWitness time,
    W.state = nativeCarryRealPlaneSampleAt sigma time

/-- A state-level pre-compression lift reconstructs the full carry mass. -/
theorem boundaryClosurePrecompressionLift_massCompatible
    {sigma time : ℝ}
    (hlift :
      NativeCarryRealPlaneBoundaryClosureHasPrecompressionLift sigma time) :
    NativeCarryRealPlaneMassCompatible sigma time := by
  rcases hlift with ⟨W, hstate⟩
  intro n hn
  rw [← congrFun hstate n]
  exact W.state_energy_eq_inverse (lt_trans (by norm_num) hn)

/-- Consequently every lifted radial readout has the critical exponent. -/
theorem boundaryClosurePrecompressionLift_sigma_eq_half
    {sigma time : ℝ}
    (hlift :
      NativeCarryRealPlaneBoundaryClosureHasPrecompressionLift sigma time) :
    sigma = (1 : ℝ) / 2 :=
  (nativeCarryRealPlaneMassCompatible_iff sigma time).1
    (boundaryClosurePrecompressionLift_massCompatible hlift)

/--
The retained witness activates the corrected conformal slope.  Its transverse
coefficient is zero because that fact has already been obtained from the
uncompressed mass, not from the scalar camera limit.
-/
theorem boundaryClosurePrecompressionLift_to_timePencil
    {sigma time : ℝ}
    (hlift :
      NativeCarryRealPlaneBoundaryClosureHasPrecompressionLift sigma time) :
    nativeCarryRealTimeMultiplicationBoundaryPencil.RelationHasConformalSlope
      time ((1 : ℝ) / 2 - sigma) := by
  rcases hlift with ⟨W, hstate⟩
  have hsigma :
      sigma = (1 : ℝ) / 2 :=
    boundaryClosurePrecompressionLift_sigma_eq_half ⟨W, hstate⟩
  have hslope := W.to_timeMultiplicationRelationHasConformalSlope
  simpa [hsigma] using hslope

/-! ## Exact guardrail for the old raw closure -/

/--
Global promotion principle from the compressed boundary limit to the retained
pre-compression state.
-/
def NativeCarryRealPlaneBoundaryClosureLiftsToPrecompression : Prop :=
  ∀ {sigma time : ℝ}, 0 < sigma → sigma < 1 →
    NativeCarryRealPlaneBoundaryClosesAt sigma time →
      NativeCarryRealPlaneBoundaryClosureHasPrecompressionLift sigma time

/--
Promoting every raw closure to the physical witness is exactly the old
zero-rigidity gate.  This prevents the new data structure from hiding the
remaining reconstruction theorem.
-/
theorem boundaryClosureLiftsToPrecompression_iff_zeroRigidity :
    NativeCarryRealPlaneBoundaryClosureLiftsToPrecompression ↔
      NativeCarryRealPlaneZeroRigidity := by
  constructor
  · intro hlifts sigma time hsigma0 hsigma1 hclose
    exact boundaryClosurePrecompressionLift_sigma_eq_half
      (hlifts hsigma0 hsigma1 hclose)
  · intro hrigid sigma time hsigma0 hsigma1 hclose
    have hsigma : sigma = (1 : ℝ) / 2 :=
      hrigid hsigma0 hsigma1 hclose
    subst sigma
    let W :=
      NativeCarryRealPrecompressionBoundaryWitness.ofCriticalBoundaryClosure
        hclose
    refine ⟨W, ?_⟩
    exact W.state_eq_native

end

end CPFormal.Analytic.Cp
