import CPFormal.Logic.StructuralPersistence
import CPFormal.Carry.PositionalCarryInverseCausalInheritance
import CPFormal.Analytic.CpQuadraticDomainCrosswalk
import CPFormal.Analytic.CpNativeCarryRealOperatorConfinement
import CPFormal.Analytic.CpNativeCarryRealPlaneComplexPackaging
import CPFormal.Analytic.CpNativeCarryFiniteCameraAlgebra
import CPFormal.Analytic.CpNaturalCameraFactor
import CPFormal.Analytic.CpNaturalEvenCameraRegularity
import CPFormal.Analytic.CpNaturalCameraAnalyticContinuation
import CPFormal.Analytic.CpCarryAmplitudeIdentification
import CPFormal.Analytic.CpCarryWeightedVerticalTfvdIdentity
import CPFormal.Analytic.CpCarryVerticalBoundaryGreenDefect
import CPFormal.Analytic.CpConnectedC2Defect

/-!
# Universal structural persistence of positional carry

This module assembles, without adding a global bridge axiom, the parts of the
carry geometry that are already certified for every material base `b ≥ 2`.

The word *invariant* has several typed meanings here:

* one carry step changes positional coordinates while preserving value;
* the carry pattern keeps certified operational ancestry through the explicit
  arithmetic tower;
* the quadratic relation `amplitude² = mass` selects the same exponent
  `1/2` in every nondegenerate base;
* the native real operator has the same radial domain in every camera, while
  its resonance predicate remains camera-indexed;
* the Green, bracket, trace, and return operators reconstruct the complete
  vertical state with the ratio `q = 1 / sqrt b`, which is exactly the
  critical carry amplitude at depth one;
* complex notation is an injective packaging of the two real coordinates and
  therefore cannot create or remove a finite camera zero;
* Green boundary defects and connected Richardson defects keep their exact,
  separately typed provenance.

The final certificate is universal over the base and camera parameters of
these concrete systems.  It does **not** say that every mathematical object is
generated by carry, that raw boundary closure supplies mass compatibility, or
that resonance times of arbitrary composite cameras are equal.
-/

open scoped ComplexConjugate InnerProduct

namespace CPFormal.Analytic.Cp

open CPFormal.Logic
open CPFormal.Carry.Positional
open CPFormal.Carry.Cp
open CPFormal.Carry.Causal
open CPFormal.Carry.InverseCausal

noncomputable section

/-! ## Base-neutral names for the carry-dressed vertical valve -/

/--
The material amplitude ratio of a positional base.

The earlier implementation used the prefix `primeCarry`, but its definition
and all results used below require only `b ≥ 2`.
-/
def baseCarryAmplitudeRatio (b : ℕ) : ℝ :=
  primeCarryAmplitudeRatio b

/-- The Green operator dressed by the amplitude ratio of an arbitrary base. -/
def baseCarryVerticalL2WeightedGreen (b : ℕ) :
    CarryVerticalL2 →L[ℂ] CarryVerticalL2 :=
  primeCarryVerticalL2WeightedGreen b

/-- The centered bracket dressed by the amplitude ratio of an arbitrary base. -/
def baseCarryWeightedVerticalCenteredBracket (b : ℕ) :
    CarryVerticalL2 →L[ℂ] CarryVerticalL2 :=
  primeCarryWeightedVerticalCenteredBracket b

/-- The two-coordinate boundary trace of an arbitrary material base. -/
def baseCarryWeightedVerticalTrace (b : ℕ) :
    CarryVerticalL2 →L[ℂ] (ℂ × ℂ) :=
  primeCarryWeightedVerticalTrace b

/-- The affine boundary return of an arbitrary material base. -/
def baseCarryWeightedVerticalReturn
    (b : ℕ) (hb : 2 ≤ b) :
    (ℂ × ℂ) →L[ℂ] CarryVerticalL2 :=
  primeCarryWeightedVerticalReturn b hb

/--
The Green ratio is not an external calibration: it is the critical carry
amplitude of the first positive depth.
-/
@[simp] theorem baseCarryAmplitudeRatio_eq_criticalAmplitude_one
    (b : ℕ) :
    baseCarryAmplitudeRatio b = criticalAmplitude b 1 := by
  exact primeCarryAmplitudeRatio_eq_criticalAmplitude_one b

/--
Exact state reconstruction in every material base:

`G_b B_b + R_b Tr_b = I`.
-/
theorem baseCarryWeightedVerticalTfvd_identity
    (b : ℕ) (hb : 2 ≤ b) :
    baseCarryVerticalL2WeightedGreen b ∘L
          baseCarryWeightedVerticalCenteredBracket b +
        baseCarryWeightedVerticalReturn b hb ∘L
          baseCarryWeightedVerticalTrace b =
      ContinuousLinearMap.id ℂ CarryVerticalL2 := by
  simpa [baseCarryVerticalL2WeightedGreen,
    baseCarryWeightedVerticalCenteredBracket,
    baseCarryWeightedVerticalReturn,
    baseCarryWeightedVerticalTrace] using
      primeCarryWeightedVerticalTfvd_identity b hb

/-- Pointwise form of the exact base-dressed reconstruction. -/
theorem baseCarryWeightedVerticalTfvd_apply
    (b : ℕ) (hb : 2 ≤ b) (x : CarryVerticalL2) :
    baseCarryVerticalL2WeightedGreen b
          (baseCarryWeightedVerticalCenteredBracket b x) +
        baseCarryWeightedVerticalReturn b hb
          (baseCarryWeightedVerticalTrace b x) =
      x := by
  have h :=
    congrArg
      (fun T : CarryVerticalL2 →L[ℂ] CarryVerticalL2 => T x)
      (baseCarryWeightedVerticalTfvd_identity b hb)
  simpa using h

/-- The boundary trace recovers exactly the data inserted by the return. -/
theorem baseCarryWeightedVerticalTrace_comp_return
    (b : ℕ) (hb : 2 ≤ b) :
    baseCarryWeightedVerticalTrace b ∘L
        baseCarryWeightedVerticalReturn b hb =
      ContinuousLinearMap.id ℂ (ℂ × ℂ) := by
  simpa [baseCarryWeightedVerticalTrace,
    baseCarryWeightedVerticalReturn] using
      primeCarryWeightedVerticalTrace_comp_return b hb

/-- The centered bracket is blind exactly to the affine return channel. -/
theorem baseCarryWeightedVerticalCenteredBracket_comp_return
    (b : ℕ) (hb : 2 ≤ b) :
    baseCarryWeightedVerticalCenteredBracket b ∘L
        baseCarryWeightedVerticalReturn b hb = 0 := by
  simpa [baseCarryWeightedVerticalCenteredBracket,
    baseCarryWeightedVerticalReturn] using
      primeCarryWeightedVerticalCenteredBracket_comp_return b hb

/-! ## The Green ledger as a concrete readout atlas -/

/-- A positional material base, with no primality or parity field. -/
abbrev CarryMaterialBase := { b : ℕ // 2 ≤ b }

/-- Identity codec for a complete vertical carry state. -/
def carryVerticalIdentityCodec :
    RestrictedCodec CarryVerticalL2 CarryVerticalL2 where
  Valid := fun _ => True
  encode := id
  decode := id
  valid_encode := by
    intro semantic
    trivial
  decode_encode := by
    intro semantic
    rfl

/--
Every material base is a different Green presentation of the same complete
vertical state.

The interior and return channels may change with the base, but their sum is
fixed by the TFVD identity.
-/
def baseCarryGreenReadoutAtlas :
    ReadoutAtlas CarryMaterialBase CarryVerticalL2 CarryVerticalL2 where
  Code := fun _ => CarryVerticalL2
  codec := fun _ => carryVerticalIdentityCodec
  semanticRead := id
  normalizedRead := fun _ x => x
  read_valid := by
    intro view code hcode
    rfl
  interior := fun view x =>
    baseCarryVerticalL2WeightedGreen view.1
      (baseCarryWeightedVerticalCenteredBracket view.1 x)
  boundary := fun view x =>
    baseCarryWeightedVerticalReturn view.1 view.2
      (baseCarryWeightedVerticalTrace view.1 x)
  ledger := by
    intro view code hcode
    exact (baseCarryWeightedVerticalTfvd_apply view.1 view.2 code).symm

/--
Changing the material base preserves the complete Green ledger.

Only the total `interior + boundary` is asserted equal; the two components are
allowed to redistribute.
-/
theorem baseCarryGreen_totalLedger_invariant
    (source target : CarryMaterialBase) (x : CarryVerticalL2) :
    (baseCarryGreenReadoutAtlas.interior target
          (baseCarryGreenReadoutAtlas.transport source target x) +
        baseCarryGreenReadoutAtlas.boundary target
          (baseCarryGreenReadoutAtlas.transport source target x)) =
      baseCarryGreenReadoutAtlas.interior source x +
        baseCarryGreenReadoutAtlas.boundary source x := by
  exact
    (baseCarryGreenReadoutAtlas.minimal_view_invariance
      source target x trivial).2.2

/--
The zero predicate of the complete reconstructed state is independent of the
material base presentation.
-/
theorem baseCarryGreen_completeState_closes_iff
    (source target : CarryMaterialBase) (x : CarryVerticalL2) :
    baseCarryGreenReadoutAtlas.Closes target
        (baseCarryGreenReadoutAtlas.transport source target x) ↔
      baseCarryGreenReadoutAtlas.Closes source x := by
  exact
    baseCarryGreenReadoutAtlas.closes_transport_iff
      source target x trivial

/-! ## Cross-presentation and multibase invariants -/

/--
Every nondegenerate positional base selects the same quadratic domain.

The numerical weights can differ with the base; what is invariant is the
compatibility predicate and its unique exponent.
-/
theorem positionalCarryMassCompatible_base_independent
    (b c : ℕ) (hb : 1 < b) (hc : 1 < c) (sigma : ℝ) :
    PositionalCarryMassCompatible b sigma ↔
      PositionalCarryMassCompatible c sigma := by
  rw [positionalCarryMassCompatible_iff b hb sigma,
    positionalCarryMassCompatible_iff c hc sigma]

/--
Universal native-zero crosswalk.

For any positional base `b > 1` and any camera width, a native zero is exactly
positional carry-mass compatibility together with the resonance of that
camera.  No primality or parity hypothesis occurs.
-/
theorem nativeCarryRealOperatorZero_iff_positionalCarryMass_and_resonance
    (b camera : ℕ) (hb : 1 < b) (sigma time : ℝ) :
    IsNativeCarryRealOperatorZero camera sigma time ↔
      PositionalCarryMassCompatible b sigma ∧
        IsNativeCarryRealOperatorResonance camera time := by
  calc
    IsNativeCarryRealOperatorZero camera sigma time ↔
        sigma = (1 : ℝ) / 2 ∧
          IsNativeCarryRealOperatorResonance camera time :=
      isNativeCarryRealOperatorZero_iff camera sigma time
    _ ↔ PositionalCarryMassCompatible b sigma ∧
          IsNativeCarryRealOperatorResonance camera time :=
      and_congr
        (positionalCarryMassCompatible_iff b hb sigma).symm
        Iff.rfl

/--
The real camera and its two-coordinate complex packaging have the same finite
zero predicate for every width, including composite widths.
-/
theorem nativeCarryRealPlaneFiniteChartAt_zero_iff_packaged_zero_all_cameras
    (camera cutoff : ℕ) (sigma time : ℝ) :
    nativeCarryRealPlaneFiniteChartAt camera cutoff sigma time = 0 ↔
      nativeCarryFiniteSaturatedChart camera cutoff
        (fun n =>
          nativeCarryRealPlaneComplexPackaging
            (nativeCarryRealPlaneSampleAt sigma time n)) = 0 := by
  simpa [nativeCarryRealPlaneFiniteChartAt] using
    (nativeCarryFiniteSaturatedChart_zero_iff_packaged_zero
      camera cutoff (nativeCarryRealPlaneSampleAt sigma time))

/-! ## A single certificate containing the already proved layers -/

/--
Certificate that gathers the concrete persistence laws belonging to one
material base.  Its fields remain separate so that equality of one readout is
never silently promoted to equality of states, cameras, or asymptotic limits.
-/
structure CarryStructuralPersistenceCertificate
    (b : ℕ) (hb : 2 ≤ b) where
  positional_decomposition :
    ∀ k n : ℕ,
      ∃! qr : ℕ × ℕ,
        qr.2 + b ^ k * qr.1 = n ∧ qr.2 < b ^ k
  carry_conserves_value :
    ∀ k : ℕ,
      positionalValue (saturatedCarryConfiguration b k) =
        positionalValue (normalizedCarryConfiguration b k)
  carry_changes_coordinates :
    ∀ k : ℕ,
      saturatedCarryConfiguration b k ≠
        normalizedCarryConfiguration b k
  causal_arithmetic :
    ∀ carrier,
      (positionalArithmeticSystem b).CausallyPresentIn
        CarryPattern.positionalCarry carrier
  inverse_arithmetic :
    PositionalInverseArithmeticCertificates b
  uniform_carry_mass :
    ∀ k : ℕ,
      uniformFiniteProbability
          (uniformCarryEvent
            (b ^ k) (pow_pos (by omega : 0 < b) k)) =
        criticalMass b k
  quadratic_amplitude :
    ∀ k : ℕ,
      (criticalAmplitude b k) ^ 2 = criticalMass b k
  green_ratio_is_carry_amplitude :
    baseCarryAmplitudeRatio b = criticalAmplitude b 1
  positional_real_domain_crosswalk :
    ∀ sigma time : ℝ,
      PositionalCarryMassCompatible b sigma ↔
        NativeCarryRealPlaneMassCompatible sigma time
  positional_radial_rigidity :
    ∀ sigma : ℝ,
      PositionalCarryMassCompatible b sigma ↔
        sigma = (1 : ℝ) / 2
  multibase_radial_invariance :
    ∀ c : ℕ, 2 ≤ c → ∀ sigma : ℝ,
      PositionalCarryMassCompatible b sigma ↔
        PositionalCarryMassCompatible c sigma
  native_zero_crosswalk :
    ∀ camera : ℕ, ∀ sigma time : ℝ,
      IsNativeCarryRealOperatorZero camera sigma time ↔
        PositionalCarryMassCompatible b sigma ∧
          IsNativeCarryRealOperatorResonance camera time
  packaged_camera_zero_invariance :
    ∀ camera cutoff : ℕ, ∀ sigma time : ℝ,
      nativeCarryRealPlaneFiniteChartAt camera cutoff sigma time = 0 ↔
        nativeCarryFiniteSaturatedChart camera cutoff
          (fun n =>
            nativeCarryRealPlaneComplexPackaging
              (nativeCarryRealPlaneSampleAt sigma time n)) = 0
  aligned_c2_is_width_four :
    ∀ cutoff : ℕ, ∀ f : ℤ → ℂ,
      nativeCarryAlignedC2Chart cutoff f =
        nativeCarryFiniteSaturatedChart 4 cutoff f
  odd_camera_finite_normal_form :
    ∀ camera cutoff : ℕ,
      Odd camera → 1 < camera → ∀ f : ℤ → ℂ,
        nativeCarryFiniteSaturatedChart camera cutoff f =
          nativeCarryPositivePrefix
              ((camera : ℤ) * (cutoff : ℤ) +
                (CPFormal.Genuine.Cp.halfRange camera : ℤ)) f -
            camera • nativeCarryCenterChannel camera cutoff f
  even_camera_finite_normal_form :
    ∀ camera cutoff : ℕ,
      Even camera → 2 < camera → ∀ f : ℤ → ℂ,
        nativeCarryFiniteSaturatedChart camera cutoff f =
          nativeCarryPositivePrefix
              ((camera : ℤ) * (cutoff : ℤ) +
                (CPFormal.Genuine.Cp.halfRange camera : ℤ)) f -
            nativeCarryDilationChannel (camera / 2) (2 * cutoff) f -
            (camera - 2) •
              nativeCarryCenterChannel camera cutoff f
  odd_composite_camera_decomposition :
    ∀ a c cutoff : ℕ,
      Odd a → Odd c → 1 < a → 1 < c → ∀ f : ℤ → ℂ,
        nativeCarryFiniteSaturatedChart (a * c) cutoff f =
          nativeCarryFiniteSaturatedChart a
              (c * cutoff + CPFormal.Genuine.Cp.halfRange c) f +
            a • nativeCarryFiniteSaturatedChart c cutoff
              (fun n => f ((a : ℤ) * n))
  odd_camera_factor_regular :
    ∀ camera : ℕ, Odd camera → 1 < camera → ∀ time : ℝ,
      naturalOddCameraFactor camera
        (nativeCarryCriticalParameter time) ≠ 0
  aligned_c2_camera_factor_regular :
    ∀ time : ℝ,
      naturalEvenCameraFactor 4
        (nativeCarryCriticalParameter time) ≠ 0
  even_camera_factor_regular :
    ∀ camera : ℕ, Even camera → 6 ≤ camera → ∀ time : ℝ,
      naturalEvenCameraFactor camera
        (nativeCarryCriticalParameter time) ≠ 0
  natural_camera_analytic_factorization :
    ∀ camera : ℕ, 3 ≤ camera → ∀ s : ℂ,
      s ∈ genuineCriticalStrip →
        bracketedDirichletChart camera s =
          naturalCameraFactor camera s * genuineContinuation s
  natural_camera_critical_zero_iff :
    ∀ camera : ℕ, 3 ≤ camera → ∀ s : ℂ,
      s.re = (1 : ℝ) / 2 →
        (bracketedDirichletChart camera s = 0 ↔
          genuineContinuation s = 0)
  aligned_c2_analytic_factorization :
    ∀ s : ℂ, s ∈ genuineCriticalStrip →
      bracketedDirichletChart 4 s =
        naturalEvenCameraFactor 4 s * genuineContinuation s
  aligned_c2_critical_zero_iff :
    ∀ s : ℂ, s.re = (1 : ℝ) / 2 →
      (bracketedDirichletChart 4 s = 0 ↔
        genuineContinuation s = 0)
  green_bracket_return_reconstruction :
    baseCarryVerticalL2WeightedGreen b ∘L
          baseCarryWeightedVerticalCenteredBracket b +
        baseCarryWeightedVerticalReturn b hb ∘L
          baseCarryWeightedVerticalTrace b =
      ContinuousLinearMap.id ℂ CarryVerticalL2
  trace_recovers_return :
    baseCarryWeightedVerticalTrace b ∘L
        baseCarryWeightedVerticalReturn b hb =
      ContinuousLinearMap.id ℂ (ℂ × ℂ)
  bracket_annihilates_return :
    baseCarryWeightedVerticalCenteredBracket b ∘L
        baseCarryWeightedVerticalReturn b hb = 0
  boundary_defect_has_exact_provenance :
    ∀ x y : CarryVerticalL2,
      inner ℂ
          ((carryWeightedVerticalBoundaryPencil
              (baseCarryAmplitudeRatio b)).fluxTrace y)
          ((carryWeightedVerticalBoundaryPencil
              (baseCarryAmplitudeRatio b)).valueTrace x) -
        inner ℂ
          ((carryWeightedVerticalBoundaryPencil
              (baseCarryAmplitudeRatio b)).valueTrace y)
          ((carryWeightedVerticalBoundaryPencil
              (baseCarryAmplitudeRatio b)).fluxTrace x) =
        carryWeightedVerticalBoundaryWronskian
          (baseCarryAmplitudeRatio b) x y
  connected_defect_has_exact_provenance :
    ∀ epsilonP epsilonQ epsilonPQ : ℝ,
      c2PairRichardsonDefect epsilonP epsilonQ epsilonPQ =
        (1 / 2) * epsilonP * epsilonQ

/--
Universal certificate theorem.

Every natural base `b ≥ 2`, prime or composite, carries all of the certified
layers assembled above.
-/
def carryStructuralPersistenceCertificate
    (b : ℕ) (hb : 2 ≤ b) :
    CarryStructuralPersistenceCertificate b hb where
  positional_decomposition := by
    intro k n
    exact positionalDecompositionAtDepth_existsUnique
      b k n (by omega)
  carry_conserves_value :=
    positionalUnitCarry_preserves_value b
  carry_changes_coordinates :=
    positionalUnitCarry_changes_configuration b
  causal_arithmetic :=
    positionalCarry_causallyPresent_through_arithmeticTower b (by omega)
  inverse_arithmetic :=
    positionalInverseArithmeticCertificates b (by omega)
  uniform_carry_mass := by
    intro k
    exact uniformCarryEvent_probability b k (by omega)
  quadratic_amplitude :=
    criticalAmplitude_sq_eq_mass b
  green_ratio_is_carry_amplitude :=
    baseCarryAmplitudeRatio_eq_criticalAmplitude_one b
  positional_real_domain_crosswalk := by
    intro sigma time
    exact positionalCarryMassCompatible_iff_realEnergyCompatible
      b (by omega) sigma time
  positional_radial_rigidity := by
    intro sigma
    exact positionalCarryMassCompatible_iff b (by omega) sigma
  multibase_radial_invariance := by
    intro c hc sigma
    exact positionalCarryMassCompatible_base_independent
      b c (by omega) (by omega) sigma
  native_zero_crosswalk := by
    intro camera sigma time
    exact nativeCarryRealOperatorZero_iff_positionalCarryMass_and_resonance
      b camera (by omega) sigma time
  packaged_camera_zero_invariance := by
    intro camera cutoff sigma time
    exact
      nativeCarryRealPlaneFiniteChartAt_zero_iff_packaged_zero_all_cameras
        camera cutoff sigma time
  aligned_c2_is_width_four :=
    nativeCarryAlignedC2Chart_eq_width_four
  odd_camera_finite_normal_form := by
    intro camera cutoff hodd hcamera f
    exact nativeCarryFiniteSaturatedChart_odd_normal_form
      camera cutoff hodd hcamera f
  even_camera_finite_normal_form := by
    intro camera cutoff heven hcamera f
    exact nativeCarryFiniteSaturatedChart_even_normal_form
      camera cutoff heven hcamera f
  odd_composite_camera_decomposition := by
    intro a c cutoff haodd hcodd ha hc f
    exact nativeCarryFiniteSaturatedChart_odd_mul_decomposition
      a c cutoff haodd hcodd ha hc f
  odd_camera_factor_regular := by
    intro camera hodd hcamera time
    exact
      naturalOddCameraFactor_ne_zero_on_criticalLine
        camera hodd hcamera
          (nativeCarryCriticalParameter_re time)
  aligned_c2_camera_factor_regular := by
    intro time
    exact
      naturalEvenCameraFactor_four_ne_zero_on_criticalLine
        (nativeCarryCriticalParameter_re time)
  even_camera_factor_regular := by
    intro camera heven hcamera time
    exact
      naturalEvenCameraFactor_nativeCarryCriticalParameter_ne_zero
        camera heven hcamera time
  natural_camera_analytic_factorization := by
    intro camera hcamera s hs
    exact
      bracketedDirichletChart_eq_naturalCameraFactor_mul_genuineContinuation
        camera hcamera hs
  natural_camera_critical_zero_iff := by
    intro camera hcamera s hs
    exact
      bracketedDirichletChart_zero_iff_genuineContinuation_zero_of_three_le
        camera hcamera hs
  aligned_c2_analytic_factorization := by
    intro s hs
    exact
      alignedC2BracketedDirichletChart_eq_factor_mul_genuineContinuation hs
  aligned_c2_critical_zero_iff := by
    intro s hs
    exact
      alignedC2BracketedDirichletChart_zero_iff_genuineContinuation_zero hs
  green_bracket_return_reconstruction :=
    baseCarryWeightedVerticalTfvd_identity b hb
  trace_recovers_return :=
    baseCarryWeightedVerticalTrace_comp_return b hb
  bracket_annihilates_return :=
    baseCarryWeightedVerticalCenteredBracket_comp_return b hb
  boundary_defect_has_exact_provenance := by
    intro x y
    exact carryWeightedVerticalBoundaryGreenDefect_eq_wronskian
      (baseCarryAmplitudeRatio b) x y
  connected_defect_has_exact_provenance :=
    c2PairRichardsonDefect_eq

/-- The universal certificate is inhabited for every nondegenerate base. -/
theorem carryStructuralPersistenceCertificate_nonempty
    (b : ℕ) (hb : 2 ≤ b) :
    Nonempty (CarryStructuralPersistenceCertificate b hb) :=
  ⟨carryStructuralPersistenceCertificate b hb⟩

end

end CPFormal.Analytic.Cp
